<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="fastlane.lanes">
    
    
    
      
      <testcase classname="fastlane.lanes" name="0: default_platform" time="0.025179">
        
      </testcase>
    
      
      <testcase classname="fastlane.lanes" name="1: gradle" time="19.024462">
        
          <failure message="/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/actions/actions_helper.rb:48:in `execute_action'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'&#10;Fastfile:21:in `block (2 levels) in parsing_binding'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/lane.rb:33:in `call'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/lane.rb:33:in `call'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:45:in `execute'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'&#10;/Users/test/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.121.1/bin/fastlane:23:in `&lt;top (required)&gt;'&#10;/Users/test/.fastlane/bin/bundle/bin/fastlane:22:in `load'&#10;/Users/test/.fastlane/bin/bundle/bin/fastlane:22:in `&lt;main&gt;'&#10;&#10;Exit status of command '/Users/test/MOWEDE/AndroidCICD/gradlew test -p .' was 1 instead of 0.&#10;Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details&#10;:app:checkDebugClasspath UP-TO-DATE&#10;:app:preBuild UP-TO-DATE&#10;:app:preDebugBuild UP-TO-DATE&#10;:app:compileDebugAidl NO-SOURCE&#10;:app:compileDebugRenderscript UP-TO-DATE&#10;:app:checkDebugManifest UP-TO-DATE&#10;:app:generateDebugBuildConfig UP-TO-DATE&#10;:app:mainApkListPersistenceDebug UP-TO-DATE&#10;:app:generateDebugResValues UP-TO-DATE&#10;:app:generateDebugResources UP-TO-DATE&#10;:app:mergeDebugResources UP-TO-DATE&#10;:app:createDebugCompatibleScreenManifests UP-TO-DATE&#10;:app:processDebugManifest UP-TO-DATE&#10;:app:splitsDiscoveryTaskDebug UP-TO-DATE&#10;:app:processDebugResources UP-TO-DATE&#10;:app:compileDebugKotlin&#10;:app:prepareLintJar UP-TO-DATE&#10;:app:generateDebugSources UP-TO-DATE&#10;:app:javaPreCompileDebug&#10;:app:compileDebugJavaWithJavac&#10;:app:compileDebugUnitTestKotlin&#10;:app:generateDebugUnitTestSources UP-TO-DATE&#10;:app:preDebugUnitTestBuild UP-TO-DATE&#10;:app:javaPreCompileDebugUnitTest&#10;:app:compileDebugUnitTestJavaWithJavac NO-SOURCE&#10;:app:processDebugJavaRes NO-SOURCE&#10;:app:processDebugUnitTestJavaRes NO-SOURCE&#10;:app:testDebugUnitTest&#10;&#10;com.mowede.androidci.ExampleUnitTest &gt; addition_isCorrect FAILED&#10;    java.lang.AssertionError at ExampleUnitTest.kt:15&#10;&#10;1 test completed, 1 failed&#10;:app:testDebugUnitTest FAILED&#10;&#10;FAILURE: Build failed with an exception.&#10;&#10;* What went wrong:&#10;Execution failed for task ':app:testDebugUnitTest'.&#10;&gt; There were failing tests. See the report at: file:///Users/test/MOWEDE/AndroidCICD/app/build/reports/tests/testDebugUnitTest/index.html&#10;&#10;* Try:&#10;Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.&#10;&#10;* Get more help at https://help.gradle.org&#10;&#10;BUILD FAILED in 18s&#10;19 actionable tasks: 6 executed, 13 up-to-date&#10;" />
        
      </testcase>
    
  </testsuite>
</testsuites>
